# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1J3XTrm1C9xXGe_TCy6pZpUs6pixziQ-T
"""

import pandas as pd
import random
import csv

 myFile=pd.read_csv("C:\\Users\\daniyal\\Desktop\\test.csv")
num = random.randint(1,0)
myFile = num
print(num)